### ISSUE TITLE
Package is not compatible with .NET 4.5

### ISSUE THREAD

**Issue by setkeh** [gitFurious/HaloSharp#4]
Could not install package 'HaloSharp 1.1.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

I would just submit a pull request but im unsure how to resolve this one if you could point me in the right direction i would be more than happy to help out :)

**Comment by gitFurious** [comment]
At the moment HaloSharp requires .NET 4.5.2.

If you *don't* have 4.5.2 you should install the [Microsoft .NET Framework 4.5.2 Developer Pack](https://www.microsoft.com/en-us/download/details.aspx?id=42637).  

If you *can't* have 4.5.2 you'll have to look at what code is using 4.5.2 features (probably just string interpolation) and replace it with 4.5 features.

If you can, update to 4.5.2 :)

**Comment by setkeh** [comment]
Thanks mate im in the process of downloading the update ill update the application to use 4.5.2 and fix what ever breaks :)

**Comment by setkeh** [comment]
For the Record i actually updated my .NET developer tools to 4.6.1 and it installs great i haven't written any code yet ill do that tomorrow night but the package works thanks again for the tip.
